[project]
name = "elixir-mastery"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "loguru>=0.7.3",
    "mypy>=1.18.2",
    "pylint>=4.0.3",
    "pytest>=9.0.1",
    "typer>=0.20.0",
]
